package in.project.main.entities.enums;

/**
 * Types of notifications generated by system and user events.
 */
public enum NotificationType {
    // 1. Account & Security
    USER_REGISTERED("User Registered", NotificationCategory.ACCOUNT, NotificationPriority.NORMAL, "bi-person-plus"),
    WELCOME_STUDENT("Welcome to EduTake", NotificationCategory.ACCOUNT, NotificationPriority.NORMAL, "bi-stars"),
    PASSWORD_CHANGED("Password Changed", NotificationCategory.ACCOUNT, NotificationPriority.HIGH, "bi-key"),
    PROFILE_UPDATED("Profile Updated", NotificationCategory.ACCOUNT, NotificationPriority.LOW, "bi-person-gear"),
    ACCOUNT_STATUS_CHANGED("Account Status Changed", NotificationCategory.ACCOUNT, NotificationPriority.HIGH, "bi-shield-exclamation"),
    SECURITY_ALERT("Security Alert", NotificationCategory.ACCOUNT, NotificationPriority.CRITICAL, "bi-shield-slash"),

    // 2. Student Management
    NEW_STUDENT("New Student Registered", NotificationCategory.STUDENT, NotificationPriority.NORMAL, "bi-mortarboard"),
    NEW_STUDENT_REGISTERED("New Student Registered", NotificationCategory.STUDENT, NotificationPriority.NORMAL, "bi-person-check"),
    STUDENT_ADDED_BY_ADMIN("Student Added by Admin", NotificationCategory.STUDENT, NotificationPriority.NORMAL, "bi-person-plus-fill"),

    // 3. Instructor Management
    NEW_INSTRUCTOR_CREATED("New Instructor Created", NotificationCategory.INSTRUCTOR, NotificationPriority.NORMAL, "bi-person-badge"),
    INSTRUCTOR_WELCOME("Welcome Instructor", NotificationCategory.INSTRUCTOR, NotificationPriority.NORMAL, "bi-award"),
    INSTRUCTOR_STATUS_CHANGED("Instructor Status Updated", NotificationCategory.INSTRUCTOR, NotificationPriority.HIGH, "bi-shield-check"),
    INSTRUCTOR_COURSE_ASSIGNED("Course Assigned", NotificationCategory.INSTRUCTOR, NotificationPriority.NORMAL, "bi-journal-plus"),
    INSTRUCTOR_COURSE_UNASSIGNED("Course Unassigned", NotificationCategory.INSTRUCTOR, NotificationPriority.NORMAL, "bi-journal-x"),

    // 4. Course & Learning
    COURSE_CREATED("Course Created", NotificationCategory.COURSE, NotificationPriority.LOW, "bi-book"),
    COURSE_PUBLISHED("Course Published", NotificationCategory.COURSE, NotificationPriority.NORMAL, "bi-send-check"),
    COURSE_UPDATED("Course Updated", NotificationCategory.COURSE, NotificationPriority.LOW, "bi-pencil-square"),
    COURSE_ARCHIVED("Course Archived", NotificationCategory.COURSE, NotificationPriority.NORMAL, "bi-archive"),
    COURSE_ATTENTION("Course Needs Attention", NotificationCategory.COURSE, NotificationPriority.HIGH, "bi-exclamation-triangle"),
    COURSE_UPDATE("Course Content Updated", NotificationCategory.COURSE, NotificationPriority.LOW, "bi-info-circle"),
    NEW_LESSON("New Lesson Available", NotificationCategory.COURSE, NotificationPriority.NORMAL, "bi-play-circle"),
    NEW_LESSON_ADDED("New Lesson Added", NotificationCategory.COURSE, NotificationPriority.NORMAL, "bi-play-circle-fill"),
    NEW_COURSE_AVAILABLE("New Course Available", NotificationCategory.COURSE, NotificationPriority.NORMAL, "bi-collection-play"),
    CERTIFICATE_READY("Certificate Ready", NotificationCategory.COURSE, NotificationPriority.NORMAL, "bi-award-fill"),

    // 5. Enrollment & Orders
    ORDER_PLACED("Order Placed", NotificationCategory.ENROLLMENT, NotificationPriority.NORMAL, "bi-bag-check"),
    NEW_ORDER("New Order Received", NotificationCategory.ENROLLMENT, NotificationPriority.NORMAL, "bi-receipt"),
    COURSE_ENROLLED("Course Enrolled", NotificationCategory.ENROLLMENT, NotificationPriority.NORMAL, "bi-mortarboard-fill"),
    COURSE_ACCESS_GRANTED("Course Access Granted", NotificationCategory.ENROLLMENT, NotificationPriority.NORMAL, "bi-unlock-fill"),
    COURSE_ACCESS_REVOKED("Course Access Revoked", NotificationCategory.ENROLLMENT, NotificationPriority.HIGH, "bi-lock-fill"),

    // 6. Payments
    PAYMENT_RECEIVED("Payment Received", NotificationCategory.PAYMENT, NotificationPriority.NORMAL, "bi-cash-coin"),
    PAYMENT_SUCCESS("Payment Successful", NotificationCategory.PAYMENT, NotificationPriority.NORMAL, "bi-check-circle-fill"),
    PAYMENT_FAILED("Payment Failed", NotificationCategory.PAYMENT, NotificationPriority.HIGH, "bi-x-circle-fill"),
    PAYMENT_REFUNDED("Payment Refunded", NotificationCategory.PAYMENT, NotificationPriority.HIGH, "bi-arrow-counterclockwise"),

    // 7. Quizzes & Assessments
    QUIZ_CREATED("Quiz Created", NotificationCategory.QUIZ, NotificationPriority.NORMAL, "bi-question-circle"),
    NEW_QUIZ_AVAILABLE("New Quiz Available", NotificationCategory.QUIZ, NotificationPriority.NORMAL, "bi-patch-question"),
    QUIZ_ATTEMPTED("Quiz Submitted", NotificationCategory.QUIZ, NotificationPriority.NORMAL, "bi-file-earmark-check"),
    QUIZ_RESULT_AVAILABLE("Quiz Result Published", NotificationCategory.QUIZ, NotificationPriority.NORMAL, "bi-clipboard-check"),

    // 8. Assignments
    ASSIGNMENT_CREATED("Assignment Created", NotificationCategory.ASSIGNMENT, NotificationPriority.NORMAL, "bi-file-earmark-plus"),
    ASSIGNMENT_SUBMITTED("Assignment Submitted", NotificationCategory.ASSIGNMENT, NotificationPriority.NORMAL, "bi-file-earmark-arrow-up"),
    ASSIGNMENT_GRADED("Assignment Graded", NotificationCategory.ASSIGNMENT, NotificationPriority.NORMAL, "bi-check2-all"),

    // 9. Announcements & Notices
    NEW_ANNOUNCEMENT("New Announcement", NotificationCategory.ANNOUNCEMENT, NotificationPriority.NORMAL, "bi-megaphone"),
    ANNOUNCEMENT_UPDATED("Announcement Updated", NotificationCategory.ANNOUNCEMENT, NotificationPriority.LOW, "bi-bell"),

    // 10. CRM & Feedback
    NEW_ENQUIRY("New Inquiry Received", NotificationCategory.STUDENT, NotificationPriority.NORMAL, "bi-chat-dots"),
    NEW_LEAD("New Lead Generated", NotificationCategory.STUDENT, NotificationPriority.NORMAL, "bi-funnel"),
    NEW_FEEDBACK("New Student Feedback", NotificationCategory.STUDENT, NotificationPriority.NORMAL, "bi-star-fill"),

    // 11. System
    SYSTEM_ANNOUNCEMENT("System Announcement", NotificationCategory.SYSTEM, NotificationPriority.NORMAL, "bi-broadcast"),
    SYSTEM_WARNING("System Alert", NotificationCategory.SYSTEM, NotificationPriority.CRITICAL, "bi-exclamation-octagon-fill");

    private final String displayName;
    private final NotificationCategory defaultCategory;
    private final NotificationPriority defaultPriority;
    private final String iconClass;

    NotificationType(String displayName, NotificationCategory defaultCategory,
                     NotificationPriority defaultPriority, String iconClass) {
        this.displayName = displayName;
        this.defaultCategory = defaultCategory;
        this.defaultPriority = defaultPriority;
        this.iconClass = iconClass;
    }

    public String getDisplayName() {
        return displayName;
    }

    public NotificationCategory getDefaultCategory() {
        return defaultCategory;
    }

    public NotificationPriority getDefaultPriority() {
        return defaultPriority;
    }

    public String getIconClass() {
        return iconClass;
    }
}
