package in.project.main.entities.enums;

/**
 * Types of notifications generated by system events.
 */
public enum NotificationType {
    // Admin notifications
    NEW_STUDENT,
    NEW_ORDER,
    PAYMENT_RECEIVED,
    NEW_ENQUIRY,
    NEW_LEAD,
    NEW_FEEDBACK,
    COURSE_ATTENTION,
    SYSTEM_WARNING,
    // Student notifications
    COURSE_ENROLLED,
    ORDER_PLACED,
    PAYMENT_SUCCESS,
    COURSE_UPDATE,
    NEW_LESSON,
    CERTIFICATE_READY
}
