package in.project.main.entities.enums;

/**
 * Types of admin notifications generated by system events.
 */
public enum NotificationType {
    NEW_STUDENT,
    NEW_ORDER,
    PAYMENT_RECEIVED,
    NEW_ENQUIRY,
    NEW_LEAD,
    NEW_FEEDBACK,
    COURSE_ATTENTION,
    SYSTEM_WARNING
}
